# Generated by Django 4.2.1 on 2023-06-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('comment', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='object/images')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='object.object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ИМЯ')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
                ('social', models.TextField(blank=True, null=True, verbose_name='Соц сети')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='object.object')),
            ],
            options={
                'verbose_name': 'Контакт объекта',
                'verbose_name_plural': 'Контакты объекта',
            },
        ),
    ]
