# Generated by Django 4.2.1 on 2023-09-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Категория Доп оборудование',
                'verbose_name_plural': 'Категория Доп оборудование',
            },
        ),
        migrations.CreateModel(
            name='AdditionalEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Модель Доп оборудование',
                'verbose_name_plural': 'Модель Доп оборудование',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер объекта\\договора')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('longtitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='часы работы')),
                ('comment', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_sign', models.BooleanField(default=False)),
                ('is_have_other_additional_equipment', models.BooleanField(default=False)),
                ('is_potencial', models.BooleanField(default=False)),
                ('address_comment', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='object/image')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ObjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='object/images')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='object.object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
                ('social', models.TextField(blank=True, null=True, verbose_name='Соц сети')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='object.object')),
            ],
            options={
                'verbose_name': 'Контакт объекта',
                'verbose_name_plural': 'Контакты объекта',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='ObjectAdditionalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.additionalequipmentmodel')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_equipments', to='object.object')),
            ],
            options={
                'verbose_name': 'Доп оборудование',
                'verbose_name_plural': 'Доп оборудование',
            },
        ),
    ]
