# Generated by Django 4.2.1 on 2023-10-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('object', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_smart',
            field=models.BooleanField(default=False, verbose_name='стороннее управление (умный дом)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_objects', to='client.client'),
        ),
    ]
