# Generated by Django 4.2.1 on 2023-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_objectfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='longtitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='work_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='часы работы'),
        ),
        migrations.AlterField(
            model_name='object',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер объекта\\договора'),
        ),
    ]
