# Generated by Django 4.2.1 on 2023-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_object_latitude_object_longtitude_object_work_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер объекта\\договора'),
        ),
        migrations.AlterField(
            model_name='objectcontact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='objectcontact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='objectcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
