# Generated by Django 4.2.1 on 2023-06-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_alter_object_number_alter_objectcontact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Категория Доп оборудование',
                'verbose_name_plural': 'Категория Доп оборудование',
            },
        ),
        migrations.CreateModel(
            name='AdditionalEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Модель Доп оборудование',
                'verbose_name_plural': 'Модель Доп оборудование',
            },
        ),
        migrations.CreateModel(
            name='ObjectAdditionalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.additionalequipmentcategory')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.additionalequipmentmodel')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_equipments', to='object.object')),
            ],
            options={
                'verbose_name': 'Доп оборудование',
                'verbose_name_plural': 'Доп оборудование',
            },
        ),
    ]
