# Generated by Django 4.2.1 on 2023-07-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_additionalequipmentcategory_additionalequipmentmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectadditionalequipment',
            name='category',
        ),
        migrations.AddField(
            model_name='additionalequipmentmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='object.additionalequipmentcategory'),
        ),
    ]
