# Generated by Django 4.2.1 on 2023-07-19 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0008_remove_objectadditionalequipment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_potencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='is_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
