# Generated by Django 4.2.1 on 2023-08-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0009_object_is_potencial_object_is_sign_object_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectcontact',
            options={'ordering': ('order_num',), 'verbose_name': 'Контакт объекта', 'verbose_name_plural': 'Контакты объекта'},
        ),
        migrations.AddField(
            model_name='objectcontact',
            name='order_num',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
