# Generated by Django 4.2.1 on 2023-09-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ИМЯ\\НАЗВАНИЕ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
                ('fiz', models.BooleanField(default=False, verbose_name='ФИЗ ЛИЦО?')),
                ('dealer', models.BooleanField(default=False, verbose_name='Дилер?')),
                ('is_panic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ИМЯ')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
                ('social', models.TextField(blank=True, null=True, verbose_name='Соц сети')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='client.client')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиента',
            },
        ),
    ]
