# Generated by Django 4.2.1 on 2023-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dealer',
            field=models.BooleanField(default=False, verbose_name='Дилер?'),
        ),
    ]
