# Generated by Django 4.2.1 on 2023-05-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ИМЯ')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
                ('social', models.TextField(blank=True, null=True, verbose_name='Соц сети')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='data.client')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиента',
            },
        ),
        migrations.CreateModel(
            name='ObjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ИМЯ')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
                ('social', models.TextField(blank=True, null=True, verbose_name='Соц сети')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='data.object')),
            ],
            options={
                'verbose_name': 'Контакт объекта',
                'verbose_name_plural': 'Контакты объекта',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
