# Generated by Django 4.2.1 on 2023-09-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Фирма оборудования',
                'verbose_name_plural': 'Фирма оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='equipment/')),
                ('file', models.FileField(blank=True, null=True, upload_to='equipment/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('show_to_client', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentfirm')),
            ],
            options={
                'verbose_name': 'Модель оборудования',
                'verbose_name_plural': 'Модель оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('qr', models.FileField(blank=True, null=True, upload_to='equipment/')),
                ('qr_with_info', models.FileField(blank=True, null=True, upload_to='equipment/')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_in_work', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_warranty', models.BooleanField(blank=True, default=False)),
                ('is_service_book_sign', models.BooleanField(blank=True, default=False)),
                ('is_at_exchange', models.BooleanField(blank=True, default=False)),
                ('warranty_ends', models.DateField(blank=True, null=True)),
                ('service_book_sign_date', models.DateField(blank=True, null=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentmodel')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
