# Generated by Django 4.2.1 on 2023-09-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='object.object'),
        ),
    ]
