# Generated by Django 4.2.1 on 2023-06-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='object',
        ),
    ]
