# Generated by Django 4.2.1 on 2023-06-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_object_client'),
        ('equipment', '0002_remove_equipment_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='object.object'),
        ),
    ]
