# Generated by Django 4.2.1 on 2023-11-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentgroup_equipmentmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
