# Generated by Django 4.2.1 on 2023-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='qr_with_info',
            field=models.FileField(blank=True, null=True, upload_to='equipment/'),
        ),
    ]
