# Generated by Django 4.2.1 on 2023-11-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_is_temp_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
