# Generated by Django 4.2.1 on 2023-06-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_qr_with_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='equipment/'),
        ),
    ]
