# Generated by Django 4.2.1 on 2023-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipmentmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='show_to_client',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
