# Generated by Django 4.2.1 on 2023-07-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipmentmodel_description_equipmentmodel_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='firm',
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='equipment.equipmentfirm'),
        ),
    ]
