# Generated by Django 4.2.1 on 2023-07-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_remove_equipment_firm_equipmentmodel_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentfirm'),
        ),
    ]
