# Generated by Django 4.2.1 on 2023-07-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipment_is_warranty_equipment_warranty_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='warranty_ends',
            field=models.DateField(blank=True, null=True),
        ),
    ]
