# Generated by Django 4.2.1 on 2023-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_alter_equipment_warranty_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_service_book_sign',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
