# Generated by Django 4.2.1 on 2023-09-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='orderchat/', verbose_name='Файл к сообщению')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_new', models.BooleanField(default=True, verbose_name='Не прочитанное сообщение')),
                ('file_saved', models.BooleanField(blank=True, default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.orderchat', verbose_name='В чате')),
            ],
            options={
                'ordering': ('createdAt',),
            },
        ),
    ]
