# Generated by Django 4.2.1 on 2023-07-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
