# Generated by Django 4.2.1 on 2023-07-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_orderchatmessage_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchatmessage',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
