# Generated by Django 4.2.1 on 2023-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_orderchatmessage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchatmessage',
            name='file_saved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
