# Generated by Django 4.2.1 on 2023-09-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_orderchatmessage_file_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderchatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderchatmessage',
            name='createdAt',
        ),
    ]
