# Generated by Django 4.2.1 on 2023-09-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_orderchatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderchatmessage',
            options={'ordering': ('createdAt',)},
        ),
        migrations.AddField(
            model_name='orderchatmessage',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
