# Generated by Django 4.2.1 on 2023-12-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_only_today_orders',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
