# Generated by Django 4.2.1 on 2023-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driving',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
