# Generated by Django 4.2.1 on 2023-06-28 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userworktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworktime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_time', to=settings.AUTH_USER_MODEL),
        ),
    ]
