# Generated by Django 4.2.1 on 2023-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
