# Generated by Django 4.2.1 on 2023-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_is_admin_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_panic',
            field=models.BooleanField(default=False),
        ),
    ]
