# Generated by Django 4.2.1 on 2023-07-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_is_panic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_panic',
        ),
    ]
