# Generated by Django 4.2.1 on 2023-08-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_userworktimetype_userworktime_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworktime',
            options={'ordering': ('start',)},
        ),
    ]
