# Generated by Django 4.2.1 on 2023-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_userworktime_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
