# Generated by Django 4.2.1 on 2023-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_subscription_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworktime',
            options={'ordering': ('date',)},
        ),
        migrations.RenameField(
            model_name='userworktime',
            old_name='end',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='userworktime',
            name='start',
        ),
        migrations.AddField(
            model_name='userworktime',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworktime',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
