# Generated by Django 4.2.1 on 2023-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_userworktime_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworktime',
            options={'ordering': ('date', 'start_time')},
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
