# Generated by Django 4.2.1 on 2023-08-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_userworktime_options_alter_userworktime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworktime',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
