# Generated by Django 4.2.1 on 2023-08-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_userworktime_is_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworktime',
            options={'ordering': ('order__number', 'date', 'start_time')},
        ),
    ]
