# Generated by Django 4.2.1 on 2023-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_telega'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telega_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
