# Generated by Django 4.2.1 on 2023-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на страницу'),
        ),
    ]
