# Generated by Django 4.2.1 on 2023-09-26 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('equipment', '0002_initial'),
        ('user', '0001_initial'),
        ('object', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagefirmselect',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklist'),
        ),
        migrations.AddField(
            model_name='stagefirmselect',
            name='equipment_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentfirm'),
        ),
        migrations.AddField(
            model_name='stagefirmselect',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firms', to='order.stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='add_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_user_role', to='user.role'),
        ),
        migrations.AddField(
            model_name='stage',
            name='btn_1_goto_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goto_stage_1_btn', to='order.stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='btn_2_goto_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goto_stage_2_btn', to='order.stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklist'),
        ),
        migrations.AddField(
            model_name='stage',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='user.role'),
        ),
        migrations.AddField(
            model_name='stage',
            name='role_can_interact',
            field=models.ManyToManyField(blank=True, null=True, related_name='role_can_interact', to='user.role'),
        ),
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.status'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.object'),
        ),
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.stage'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.type'),
        ),
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.worktype'),
        ),
        migrations.AddField(
            model_name='checklisttableinput',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklisttableinputfield'),
        ),
        migrations.AddField(
            model_name='checklisttableinput',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_list_table_inputs', to='order.checklisttable'),
        ),
        migrations.AddField(
            model_name='checklisttabledata',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklist'),
        ),
        migrations.AddField(
            model_name='checklisttabledata',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_list_table_datas', to='order.order'),
        ),
        migrations.AddField(
            model_name='checklisttabledata',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklisttable'),
        ),
        migrations.AddField(
            model_name='checklisttable',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_list_tables', to='order.checklist'),
        ),
        migrations.AddField(
            model_name='checklistinput',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='order.checklist'),
        ),
        migrations.AddField(
            model_name='checklistinput',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.inputfield'),
        ),
        migrations.AddField(
            model_name='checklistdata',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklist'),
        ),
        migrations.AddField(
            model_name='checklistdata',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='order.order'),
        ),
    ]
