# Generated by Django 4.2.1 on 2023-10-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='btn_1_goto_stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='btn_1_label',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='btn_2_goto_stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='btn_2_label',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='check_list',
        ),
        migrations.CreateModel(
            name='StageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('goto_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goto_stage', to='order.stage')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='order.stage')),
            ],
        ),
    ]
