# Generated by Django 4.2.1 on 2023-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfield',
            name='label',
        ),
        migrations.AddField(
            model_name='checklistinput',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
