# Generated by Django 4.2.1 on 2023-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_inputfield_label_checklistinput_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='btn_1_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='btn_2_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
