# Generated by Django 4.2.1 on 2023-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_stage_btn_1_goto_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttableinputfield',
            name='grow',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
