# Generated by Django 4.2.1 on 2023-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_stage_btn_1_label_stage_btn_2_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='is_date',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
