# Generated by Django 4.2.1 on 2023-10-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentgroup_equipmentmodel_group'),
        ('order', '0004_checklisttableinputfield_grow'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageGroupSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklist')),
                ('equipment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentgroup')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='order.stage')),
            ],
        ),
        migrations.DeleteModel(
            name='StageFirmSelect',
        ),
    ]
