# Generated by Django 4.2.1 on 2023-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_inputfield_is_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistinput',
            options={'ordering': ('order_num',)},
        ),
        migrations.AddField(
            model_name='checklistinput',
            name='order_num',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
