# Generated by Django 4.2.1 on 2023-06-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role_user_role'),
        ('order', '0006_alter_checklistinput_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role'),
        ),
    ]
