# Generated by Django 4.2.1 on 2023-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='use_sms',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
