# Generated by Django 4.2.1 on 2023-12-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_use_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('check_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListTableHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('history_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checklisthistory')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.checklisttable')),
            ],
        ),
    ]
