# Generated by Django 4.2.1 on 2023-06-14 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_stage_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worker',
        ),
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
