# Generated by Django 4.2.1 on 2023-06-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_object'),
        ('order', '0008_remove_order_worker_order_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='equipment.equipment'),
        ),
    ]
