# Generated by Django 4.2.1 on 2023-12-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_checklistdatahistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisthistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
