# Generated by Django 4.2.1 on 2023-06-21 12:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_stagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='status',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
