# Generated by Django 5.0.1 on 2024-01-24 15:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_checklisthistory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='status',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
