# Generated by Django 4.2.1 on 2023-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_status_bg_color_status_text_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='is_check_list_done',
            new_name='is_default',
        ),
        migrations.AddField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='is_default',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
