# Generated by Django 4.2.1 on 2023-06-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_is_check_list_done_stage_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistdata',
            name='stage',
        ),
        migrations.AlterField(
            model_name='checklistdata',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='order.order'),
        ),
        migrations.AlterField(
            model_name='stagelog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='order.order'),
        ),
    ]
