# Generated by Django 4.2.1 on 2023-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_checklistdata_stage_alter_checklistdata_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
