# Generated by Django 4.2.1 on 2023-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
