# Generated by Django 4.2.1 on 2023-06-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_stage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-is_critical',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='checklistinput',
            name='input_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checklistinput',
            name='labels',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inputfield',
            name='is_boolean_with_input',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='inputfield',
            name='is_multiple_boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='inputfield',
            name='is_multiple_boolean_with_input',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
