# Generated by Django 4.2.1 on 2023-07-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_stage_add_user_role_stage_add_user_role_btn_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_created_by_client',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
