# Generated by Django 4.2.1 on 2023-07-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_is_created_by_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-is_critical', '-date_created_at', 'is_done'), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
