# Generated by Django 4.2.1 on 2023-07-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
