# Generated by Django 4.2.1 on 2023-07-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_checklistdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
