# Generated by Django 4.2.1 on 2023-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_checklistdata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
