# Generated by Django 4.2.1 on 2023-07-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_date_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputfield',
            old_name='is_date',
            new_name='is_separator',
        ),
    ]
