# Generated by Django 4.2.1 on 2023-08-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_rename_is_date_inputfield_is_separator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_time_left',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
