# Generated by Django 4.2.1 on 2023-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_is_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_order_for_additional_equipment',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
