# Generated by Django 4.2.1 on 2023-09-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_telega_id'),
        ('order', '0029_order_is_order_for_additional_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='role',
        ),
        migrations.AddField(
            model_name='stage',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='user.role'),
        ),
    ]
