# Generated by Django 4.2.1 on 2023-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_telega_id'),
        ('order', '0030_remove_stage_role_stage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='role_can_interact',
            field=models.ManyToManyField(blank=True, null=True, related_name='role_can_interact', to='user.role'),
        ),
    ]
